### ISSUE TITLE
OSFClient.jl / Features I would want

### ISSUE THREAD

**Issue by behinger** [JuliaAPlavin/OpenScienceFramework.jl#2]
Hi!
Thanks again for pointing me to OpenScienceFramework.jl - it looks very polished and nice. Somehow I missed it - indeed, if I google "openscienceframework.jl" - I'm pointed to my own repository (which I'm sure I'll deprecate and point to this one here, once the features I require are there :)).
![grafik](https://github.com/user-attachments/assets/2318f1ae-b0ea-40c3-9a9b-a9e6d6e6f368)

Features that I think are currently missing in OpenScienceFramework.jl:
- list & download directories without token
- download & save files based on regex/glob patterns

I looked into it a little bit:
```julia
osf = client(token="") # this could be a default for read-only access?
```
so this works, great! But then how do I access a project that I dont own?

```julia
node_id = "hk9g4"
project(osf;title=node_id)
```
doesnt work, because it tries to authenticate the user first & somehow defines some relationship calls that I dont understand.

Next I looked more into it, and hoped that this works as a start:
```julia
ent = OSF.API.get_entity(osf,:nodes,node_id)
```
nice that works!

```julia
proj = OSF.Project(osf,ent)
dir = readdir(OSF.Directory,proj) # nice! it does something at least
files =  readdir(OSF.File,dir[2])[1] # get files? -> ah, this only gets the files of the current directory, but I want all files
```
So I'm already happy with what I found out, but it was not straight forward to figure out. I think the documentation on the Readme.md is a bit hard to understand and clearly written with a "generate a new project" mindset instead of "downloading an existing project" mindset (which I have ^^)

----

Similar to what I have in [OSFClient.jl (see tutorial here)](https://www.s-ccs.de/OSFClient.jl/dev/osf_basics/) I'd want to do something like:
```julia
d = readdir(OSF.Directory,"hk9g4")
```
(Which I parsed into a FileTrees.jl structure for ease of working with a folder struct + parsing + potentially multi-threaded downloading / saving), then I can do something akin to:

```julia
download(d,save_path;pattern=glob("*/*/*.txt")
```

I'm happy to provide some implementation/PR, but first of all I need to make sure this is somethign you'd be interested to support, before diving completely into your library.

- I would need to understand better what the "storage" struct does
- Is there a way to automatically "traverse" the whole folder structure already?

**Comment by aplavin** [comment]
Thanks for the details, suggestions, and explanations! This is definitely within scope of the package.

> list & download directories without token

Oh, I didn't even know OSF API supports that! I guess `token=""` is a reasonable default, then we'll need to fix and test that it actually works for projects.

> download(d,save_path;pattern=glob("*/*/*.txt")

This functionality is useful indeed, we just need to think of the proper API. The goal of OpenScienceFramework.jl is that one can use the exact same code with regular files (using base Julia API) and with remote OSF files. Current functions like `readdir` are designed with this goal in mind.
I'm not too familiar with Glob.jl, so it would be useful if you outline how your target workflow looks for regular local files. Then we can try copying this interface to OSF.

**Comment by behinger** [comment]
Awesome!

- I guess without token we have to make sure, that all the write operations run into a "not permitted" or similar error.
- Have you ever looked into `FileTrees.jl`? 
- I guess Glob or Regex is just one way to select files to be downloaded. In my usecase I often have GB's of files and want to download only a subset of files. 
- While I understand you want to have an API that allows you to mkdir/remove etc. as if these files are on your harddrive (which is awesome!), I'm not sure this is that useful for downloading. Would this mean a `cp` to a local folder? e.g. `cp(d::OSF.Files,local_path)` instead of a download? is that explicit enough?

**Comment by aplavin** [comment]
> Have you ever looked into FileTrees.jl?

I looked into it briefly, just didn't find it useful for any of my usecases.

> In my usecase I often have GB's of files and want to download only a subset of files.

It makes sense to have an API to select files by a glob/regex on their name. I just prefer to avoid introducing APIs that are only present in OSF, better to reuse an already existing workflow from a wider community.

For example, I see that Glob has an API like `readdir(glob"...", directory)`. This can directly be replicated here, for OSF directories!

Selecting and downloading files are two separate operations, so "select files matching a pattern" and "download a collection of files" should naturally be separate functions.

> Would this mean a cp to a local folder? e.g. cp(d::OSF.Files,local_path) instead of a download? is that explicit enough?

Yeah, `cp` for downloading may be a bit too clever (or may be not)...
Currently, we have `cp` for single files here in OSF.jl: https://github.com/JuliaAPlavin/OpenScienceFramework.jl/blob/00000000872cd63a34bf623ad7d7e957f80ba333/src/highlevel.jl#L145-L153. It's a really thin wrapper for `download(url(...))`.

So, I guess both `download(file)`/`download(collection_of_files)` and corresponding `cp` functions could be implemented.

**Comment by behinger** [comment]
- where I find FileTrees.jl useful is to get an overview of the current direction. Right now there are no show methods, and plain readdir output is very verbose (and as mentioned before, there is no "traverse" function, e.g. a function akin to `tree` in the commandline - maybe worth to have at the cost of that dependency?)
- One problem, why I traverse the directory structure first, and then pattern-select, was with `osfclient` in python - where for each download of a file, the whole tree had to be searched via API - which o.c. for many files is insanely slow. I would prefer if we somehow could have a local copy of the remote filestructure (why I like FileTrees so much ;)), and sync that only on demand

**Comment by aplavin** [comment]
I see that there are many separate independent questions/requests here...

> get an overview of the current direction. Right now there are no show methods, and plain readdir output is very verbose

Adding nice `show()` methods for OSF.jl objects would be great! I simply never came to it.

> there is no "traverse" function, e.g. a function akin to tree in the commandline - maybe worth to have at the cost of that dependency

Such a function would definitely be useful. Julia provides `walkdir()` to traverse a local directory, OSF.jl should totally support `walkdir(OSF.Directory)`! It would almost work automatically, if only Julia's walkdir didn't restrict its output to strings...

> where for each download of a file, the whole tree had to be searched via API - which o.c. for many files is insanely slow

We should totally avoid that, which as I understand is possible in a straightforward manner.
Getting a file download URL from `OSF.File` doesn't require any internet requests, if you already know the "view link" for the project (which is presumably not needed for anynomous access).
So, if we have a function (like `walkdir` or `readdir` or `readdir(glob"")`) that returns a list of matching `Files`, then we can download them as a separate step without incurring any overhead.

Would that have any issues?

**Comment by behinger** [comment]
back from 🌴.

I'm now using these simple show functions:
```
import Base.show
function Base.show(io::IO, p::Project)
    println(io, "OSF-Project\n title: $(p.entity.attributes[:title]) \n id: $(p.entity.id)")
end

function Base.show(io::IO, f::File)
    println(io, "$(f.entity.attributes[:materialized_path]) => $(f.entity.attributes[:guid])")
end
function Base.show(io::IO, f::Directory)
    println(io, "$(f.entity.attributes[:materialized_path])")
end
```
they make my life a bit easier navigating osf.

A (probably too) naive version of walkdir could be:
```
import Base.walkdir
function Base.walkdir(dir::Directory)
    files = readdir(File, dir)
    dirs = readdir(Directory, dir)
    for d in dirs
        dir_files = walkdir(d)
        push!(files, dir_files...)
    end
    return files
end
```

which returns in my case 
```
4-element Vector{OpenScienceFramework.File}:
 /folderA/photo_2021-01-10_21-45-02.jpg => uy29v

 /folderA/folderA2/erp_Unbenannt.svg => fqj82

 /folderA/folderA2/example.txt => 73aym

 /folderA/folderA2/exampleB.txt => v7tze
```

The thing missing would be the Glob and/or regex search to filter the list either prior to `readdir`/`walkdir` or to the download function.

**Comment by aplavin** [comment]
> these simple show functions

Nice show methods definitely welcome!

>  (probably too) naive version of walkdir

Base.walkdir, Glod.readdir etc support – would also be nice! But please ensure that their interface is the same as the original methods that work on strings. In particular, your `walkdir` example doesn't do the same as `walkdir(::String)`:

> walkdir(dir; topdown=true, follow_symlinks=false, onerror=throw)
>  Return an iterator that walks the directory tree of a directory. **The iterator returns a tuple containing (rootpath, dirs, files).**

**Comment by behinger** [comment]
ok question you might be able to answer - in order to save API access, I tried to implement this:
```
function Base.readdir(::Tuple{Type{Directory},Type{File}}, dir::Directory)
    entities = API.relationship_complete(client(dir), dir.entity, :files)
    [
        Directory(project(dir), dir.storage, ent)
        for ent in entities
    ]
end
```
allowing for the tuple of directory/file to download both files&directories directly. But somehow this doesnt work - maybe Julia can't dispatch on types of tuples? I could implemented `Base.readdir(dir::Directory)` instead?

----
Anyway, I finished a base-conform walkdir implementation similarly returning a channel / iterator. O.c. the channels are now not string based but Directory/File based.

```julia
import Base.walkdir

function Base.walkdir(dir::Directory; topdown=true, onerror=throw)
    function _walkdir(chnl, dir)
        tryf(f, p) =
            try
                f(p)
            catch err
                isa(err, IOError) || rethrow()
                try
                    onerror(err)
                catch err2
                    close(chnl, err2)
                end
                return
            end
        files, dirs = tryf(_readdirx, dir)

        if topdown
            push!(chnl, (dir, dirs, files))
        end
        for d in dirs
            _walkdir(chnl, d)
        end
        if !topdown
            push!(chnl, (dir, dirs, files))
        end
        nothing
    end
    return Channel{Tuple{Directory,Vector{Directory},Vector{File}}}(chnl -> _walkdir(chnl, dir))
end


function _readdirx(dir::Directory)
    files = readdir(File, dir)
    dirs = readdir(Directory, dir)
    return files, dirs
end
```
The `IOError` part I took from Base - I dont know what kind of errors could happen for the current implementation. Either remove or change.

---

When implementing glob or regex, we cannot use the `readdir(glob"my/*/path")` interface because we are working on `Directory`'s. Any preferences for the interface? A keyword argument `filter`? 

---

I can prepare a PR if you prefer discussing there after resolving the issues mentioned here

**Comment by aplavin** [comment]
I added readdir(osf_dir) and some other simple methods, please take a look!
Feel free to make a PR with walkdir()! The added `readdir` should help keeping `walkdir()` implementation very close to Base :)

**Comment by behinger** [comment]
ok, I moved my things there.

Mh - downloading throws an error that no credentials are provided, even though itis a public project. Why do you use `view_only_links`?

**Comment by aplavin** [comment]
Believe it or not, I just never used it with public projects :) A PR adding anonymous download support would definitely be welcome (just ensure it doesn't break existing workflows).

**Comment by aplavin** [comment]
Relevant functionality should be available now
